image: maven:3-jdk-14

variables:
  MAVEN_CLI_OPTS: "--batch-mode clean"
  MAVEN_CLI_LEGACY_OPTS: "--legacy-local-repository"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

stages:
  - syntax
  - build
  - test
  - report
  - pages
  - deploy

syntax-check:
  stage: syntax
  script:
    - mvn $MAVEN_CLI_OPTS validate

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

report:
  stage: report
  script:
    - mvn $MAVEN_CLI_OPTS $MAVEN_CLI_LEGACY_OPTS site
  artifacts:
    paths:
      - target/site

pages:
  stage: pages
  script:
    - mvn $MAVEN_CLI_OPTS $MAVEN_CLI_LEGACY_OPTS site
    - mvn sonar:sonar
    - mv ./target/site ./target/public
    - mv ./target/public .
  artifacts:
    paths:
      - public
  only:
    - master

deliverable:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS $MAVEN_CLI_LEGACY_OPTS package
    - mvn $MAVEN_CLI_LEGACY_OPTS site
    - mv ./target/*.jar ./target/"${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.jar"
    - mv ./target ./deliverables-"${CI_COMMIT_TAG}"
  artifacts:
    name: deliverables
    expire_in: 6 mos
    paths:
      - deliverables-${CI_COMMIT_TAG}
  only:
    - /^v.*$/
